/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as InvestigationRouteImport } from './routes/investigation'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmployeeIdRouteImport } from './routes/employee/$id'

const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigationRoute = InvestigationRouteImport.update({
  id: '/investigation',
  path: '/investigation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeIdRoute = EmployeeIdRouteImport.update({
  id: '/employee/$id',
  path: '/employee/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/investigation': typeof InvestigationRoute
  '/leaderboard': typeof LeaderboardRoute
  '/simulator': typeof SimulatorRoute
  '/employee/$id': typeof EmployeeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/investigation': typeof InvestigationRoute
  '/leaderboard': typeof LeaderboardRoute
  '/simulator': typeof SimulatorRoute
  '/employee/$id': typeof EmployeeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/investigation': typeof InvestigationRoute
  '/leaderboard': typeof LeaderboardRoute
  '/simulator': typeof SimulatorRoute
  '/employee/$id': typeof EmployeeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/investigation'
    | '/leaderboard'
    | '/simulator'
    | '/employee/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/investigation' | '/leaderboard' | '/simulator' | '/employee/$id'
  id:
    | '__root__'
    | '/'
    | '/investigation'
    | '/leaderboard'
    | '/simulator'
    | '/employee/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InvestigationRoute: typeof InvestigationRoute
  LeaderboardRoute: typeof LeaderboardRoute
  SimulatorRoute: typeof SimulatorRoute
  EmployeeIdRoute: typeof EmployeeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigation': {
      id: '/investigation'
      path: '/investigation'
      fullPath: '/investigation'
      preLoaderRoute: typeof InvestigationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/$id': {
      id: '/employee/$id'
      path: '/employee/$id'
      fullPath: '/employee/$id'
      preLoaderRoute: typeof EmployeeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InvestigationRoute: InvestigationRoute,
  LeaderboardRoute: LeaderboardRoute,
  SimulatorRoute: SimulatorRoute,
  EmployeeIdRoute: EmployeeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
