"""
PHANTOM – Engine 3: Multi-Party Collusion Graph Scorer
=======================================================
Detects suspicious co-access overlaps on high-value records between
employees within a short time window, using a bipartite NetworkX graph.

Integrated with PSB Hackathon data pipeline (d.py):
Generates co-access events directly from `access_logs.csv` by looking at
module overlaps within a sliding time window.
"""

import argparse
import csv
import json
import math
import os
from collections import defaultdict
from datetime import datetime
from typing import Any, Dict, List, Optional

import networkx as nx

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
MAX_CO_ACCESS_RECORDS = 20
HOT_WINDOW_MINUTES = 120
COLLUSION_THRESHOLD = 10

# ---------------------------------------------------------------------------
# PSB Hackathon Data Integration
# ---------------------------------------------------------------------------

def extract_events_from_psb_data(access_logs_csv_path: str) -> List[Dict[str, Any]]:
    """
    Parses `access_logs.csv` (generated by d.py) and extracts synthetic 
    co-access events when employees access the same module within HOT_WINDOW_MINUTES.
    """
    if not os.path.exists(access_logs_csv_path):
        return []

    logs = []
    with open(access_logs_csv_path, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            try:
                ts = datetime.strptime(row['timestamp'], "%Y-%m-%d %H:%M:%S")
            except ValueError:
                continue
            logs.append({
                "employee_id": row["employee_id"],
                "timestamp": ts,
                "module": row["module"]
            })
            
    # Sort strictly by time to enable fast sliding-window pairs
    logs.sort(key=lambda x: x["timestamp"])
    
    events = []
    for i, l1 in enumerate(logs):
        # Look ahead within the time window
        for j in range(i + 1, len(logs)):
            l2 = logs[j]
            delta_mins = (l2["timestamp"] - l1["timestamp"]).total_seconds() / 60.0
            
            if delta_mins > HOT_WINDOW_MINUTES:
                break
                
            # If same module accessed by different employees within window
            if l1["module"] == l2["module"] and l1["employee_id"] != l2["employee_id"]:
                events.append({
                    "employee_ids": [l1["employee_id"], l2["employee_id"]],
                    "record_id": f"MOD-{l1['module'].upper().replace(' ', '_')}",
                    "delta_minutes": delta_mins,
                    "record_value": "HIGH"  # Default assumption for risk profiling
                })
                
    return events


# ---------------------------------------------------------------------------
# Graph builder
# ---------------------------------------------------------------------------

def _build_bipartite_graph(employee_id: str,
                            co_access_events: List[Dict[str, Any]]) -> nx.Graph:
    """
    Build a bipartite graph:
      - Left  nodes: employee IDs  (type='employee')
      - Right nodes: record IDs    (type='record')
    """
    G = nx.Graph()

    for event in co_access_events:
        emp_ids = event.get("employee_ids", [])
        record = event.get("record_id", "unknown")
        delta = event.get("delta_minutes", HOT_WINDOW_MINUTES)
        value = event.get("record_value", "HIGH")

        if employee_id not in emp_ids:
            continue

        time_weight = 1.5 if delta <= HOT_WINDOW_MINUTES else 0.5
        value_weight = {"HIGH": 1.5, "MEDIUM": 1.0, "LOW": 0.5}.get(value, 1.0)
        edge_weight = time_weight * value_weight

        for eid in emp_ids:
            if not G.has_node(eid):
                G.add_node(eid, type="employee")
        if not G.has_node(record):
            G.add_node(record, type="record")

        for eid in emp_ids:
            if G.has_edge(eid, record):
                G[eid][record]["weight"] += edge_weight
            else:
                G.add_edge(eid, record, weight=edge_weight)

    return G


# ---------------------------------------------------------------------------
# Core scoring
# ---------------------------------------------------------------------------

def calculate_collusion_score(employee_id: str,
                               co_access_events: List[Dict[str, Any]]) -> int:
    """
    Compute a collusion risk score for *employee_id* given co-access events.
    """
    if not co_access_events:
        return 0

    G = _build_bipartite_graph(employee_id, co_access_events)

    if employee_id not in G:
        return 0

    record_neighbors = [
        n for n in G.neighbors(employee_id) if G.nodes[n]["type"] == "record"
    ]
    shared_count = len(record_neighbors)

    weighted_degree = sum(
        G[employee_id][r]["weight"] for r in record_neighbors
    )

    co_accessors: set = set()
    for rec in record_neighbors:
        for nb in G.neighbors(rec):
            if nb != employee_id and G.nodes[nb]["type"] == "employee":
                co_accessors.add(nb)
    co_accessor_count = len(co_accessors)

    record_ratio = min(shared_count / MAX_CO_ACCESS_RECORDS, 1.0)
    max_weighted = MAX_CO_ACCESS_RECORDS * 2.25
    weight_ratio = min(weighted_degree / max_weighted, 1.0)
    accessor_ratio = min(math.log1p(co_accessor_count) / math.log1p(5), 1.0)

    raw = 0.50 * record_ratio + 0.30 * weight_ratio + 0.20 * accessor_ratio
    score = raw * 100 * 0.85

    return int(min(100, max(0, round(score))))


# ---------------------------------------------------------------------------
# D3.js graph export
# ---------------------------------------------------------------------------

def export_graph_json(employee_id: str,
                      co_access_events: List[Dict[str, Any]]) -> Dict[str, Any]:
    G = _build_bipartite_graph(employee_id, co_access_events)

    nodes = [
        {
            "id": n,
            "type": G.nodes[n].get("type", "unknown"),
            "group": 0 if G.nodes[n].get("type") == "employee" else 1,
        }
        for n in G.nodes()
    ]

    links = [
        {
            "source": u,
            "target": v,
            "weight": round(G[u][v]["weight"], 3),
        }
        for u, v in G.edges()
    ]

    return {"nodes": nodes, "links": links}


# ---------------------------------------------------------------------------
# Helper: build synthetic Day-11 co-access events (Original stub)
# ---------------------------------------------------------------------------

def build_day11_events() -> List[Dict[str, Any]]:
    events = []
    for i in range(1, 16):
        events.append(
            {
                "employee_ids": ["E1", "E3"],
                "record_id": f"ACC-HV-{i:03d}",
                "delta_minutes": 7 * i,
                "record_value": "HIGH",
            }
        )
    return events


# ---------------------------------------------------------------------------
# CLI entry-point
# ---------------------------------------------------------------------------

def _parse_args():
    parser = argparse.ArgumentParser(
        description="PHANTOM Engine 3 – Multi-Party Collusion Graph Scorer"
    )
    parser.add_argument(
        "--employee",
        default="EMP001",
        help="Employee ID to score",
    )
    parser.add_argument(
        "--day11",
        action="store_true",
        help="Run with the built-in Day-11 scenario",
    )
    parser.add_argument(
        "--events-json",
        default=None,
        help="Path to a JSON file containing co_access_events list",
    )
    parser.add_argument(
        "--psb_data",
        default="",
        help="Path to access_logs.csv from PSB Data folder",
    )
    return parser.parse_args()


def main():
    args = _parse_args()

    events = []
    if args.day11:
        events = build_day11_events()
    elif args.events_json:
        with open(args.events_json, "r") as fh:
            events = json.load(fh)
    elif args.psb_data:
        print(f"[*] Extracting windowed co-access events from {args.psb_data} ...")
        events = extract_events_from_psb_data(args.psb_data)
        print(f"[*] Found {len(events)} total pairs.")

    score = calculate_collusion_score(args.employee, events)
    graph = export_graph_json(args.employee, events)

    print(f"Employee         : {args.employee}")
    print(f"Collusion Score  : {score}/100")
    print(f"Graph nodes      : {len(graph['nodes'])}")
    print(f"Graph links      : {len(graph['links'])}")

if __name__ == "__main__":
    main()
